spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
#        show-sql: true
    hibernate:
      ddl-auto: create
#    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace

  security:
    basic:
      enabled: false
